name: Avicaubuntu

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest

    steps:
      - name: Downloading & Installing Essentials
        run: |
          curl -o Downloads.sh "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downloads.bat"
          chmod +x Downloads.sh
          ./Downloads.sh

      - name: Show Website
        run: |
          chmod +x show.sh
          ./show.sh

      - name: Time Counter
        run: |
          chmod +x loop.sh
          ./loop.sh
