name: Setup VNC Server

on: [push, workflow_dispatch]

jobs:
  setup-vnc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install VNC and XFCE
      run: |
        sudo apt update
        sudo apt install -y tigervnc-standalone-server tigervnc-common xfce4 xfce4-goodies

    - name: Set VNC password
      run: |
        mkdir -p ~/.vnc
        echo "yourpassword" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd

    - name: Create xstartup file
      run: |
        cat > ~/.vnc/xstartup <<EOF
        #!/bin/sh
        unset SESSION_MANAGER
        unset DBUS_SESSION_BUS_ADDRESS
        exec startxfce4 &
        EOF
        chmod +x ~/.vnc/xstartup

    - name: Start VNC server
      run: |
        vncserver :1 -geometry 1280x800 -depth 24
        echo "VNC server started on display :1"

    - name: Get the server's IP address and port
      run: |
        # Retrieve the IP address (this is the internal IP for the GitHub runner)
        SERVER_IP=$(hostname -I | awk '{print $1}')
        
        # VNC port is typically 5901 for display :1
        VNC_PORT=5901
        
        # Output the IP and port to GitHub Actions logs
        echo "VNC server is running at $SERVER_IP:$VNC_PORT"
        echo "VNC password is 'yourpassword'"  # Be cautious here for security reasons
        echo "::set-output name=ip::$SERVER_IP"
        echo "::set-output name=port::$VNC_PORT"

    - name: Display active ports
      run: |
        # Check if the VNC server is running and output the open ports
        netstat -tuln | grep 5901
